version: 0.0
os: linux
files:
  - source: target/*.jar
    destination: /home/ec2-user/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/craft-app-service-restart.sh
      timeout: 3600