version: '3.3'
services:
  db:
    image: 'mysql'
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
  adminer:
    image: 'adminer'
    ports:
      - '8081:8080'