spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        formart_sql: true
        dll-auto: none
   show-sql: true

  servlet:
    multipart:
      # max file size - default 1MB
      max-file-size: 10MB
      # max request size - default 10MB
      max-request-size: 25MB

config:
  contas:
    energia:
      - celpe
    cartao:
      - nu pagamentos
    aluguel:
      - conceito trans mobi
    celular:
      - tim celular
    condominio:
      - pjbank pagamentos
    internet:
      - tim sa
    agua:
      - compesa