spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username:
    password:
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    formart_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      # max file size - default 1MB
      max-file-size: 10MB
      # max request size - default 10MB
      max-request-size: 25MB

config:
  bills:
    energia:
      - celpe
    cartao:
      - nu pagamentos
    aluguel:
      - conceito trans imobi
    celular:
      - tim celular
    condominio:
      - pjbank pagamentos
    internet:
      - tim sa
    agua:
      - compesa
  targets:
    -
      label: "valor a pagar"
      amountPosition: "down"
    -
      label: "valor"
      amountPosition: "down"


