spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username:
    password:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    formart_sql: true

  servlet:
    multipart:
      # max file size - default 1MB
      max-file-size: 10MB
      # max request size - default 10MB
      max-request-size: 25MB

config:
  contas:
    energia:
      - celpe
    cartao:
      - nu pagamentos
    aluguel:
      - conceito trans mobi
    celular:
      - tim celular
    condominio:
      - pjbank pagamentos
    internet:
      - tim sa
    agua:
      - compesa