cloud:
  aws:
    region:
      static: us-east-1
    s3:
      bucket:
        name: craft-payment

server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,America/Recife

spring:
  config:
    import: aws-secretsmanager:prod/craft-core
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    formart_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      # max file size - default 1MB
      max-file-size: 10MB
      # max request size - default 10MB
      max-request-size: 25MB

config:
  bills:
    energia:
      - celpe
    cartao:
      - nu pagamentos
    aluguel:
      - conceito trans imobi
    celular:
      - tim celular
    condominio:
      - pjbank pagamentos
    internet:
      - tim sa
    agua:
      - compesa
    alimentacao:
      - ifood
      - lfood
  labelTargets:
    - "valor a pagar"
    - "valor"
    - "pix enviado"
    - "valor original"



